"""add saved_offers table

Revision ID: 6f287adc3385
Revises: 356c2e4f01f5
Create Date: 2026-06-19 20:48:49.352471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6f287adc3385'
down_revision: Union[str, None] = '356c2e4f01f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'offer_id', name='uq_saved_offers_user_offer')
    )
    op.create_index(op.f('ix_saved_offers_id'), 'saved_offers', ['id'], unique=False)
    op.create_index(op.f('ix_saved_offers_user_id'), 'saved_offers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_offers_user_id'), table_name='saved_offers')
    op.drop_index(op.f('ix_saved_offers_id'), table_name='saved_offers')
    op.drop_table('saved_offers')
    # ### end Alembic commands ###
